import type { CardDef } from '@duskline/core';
import { ASH_ID } from '@duskline/core';
import { card } from './helpers';

/**
 * Cards any Lamplighter can carry. A Lamplighter fights with what they pin to paper: their own
 * techniques, Fades they have bound, and whatever the Gnomon gives back to them.
 *
 * Numbers to keep in mind: 4 Light a turn, a hand of 3, and a Fade on the lower floors hits for 4 to 8.
 * A 1-Light card is worth about 7 to 9 points of damage and ward together.
 */

// ---------------------------------------------------------------------------
// Basics and curses
// ---------------------------------------------------------------------------

export const BASICS: readonly CardDef[] = [
  card({
    id: 'cut',
    name: 'Lamp Cut',
    kind: 'strike',
    cost: 1,
    atk: 6,
    ward: 1,
    plus: { atk: 9 },
    tier: 'basic',
    source: 'basic',
    flavor: 'The first thing every Lamplighter learns: the lamp is also a club.',
    glyph: 'blade',
  }),
  card({
    id: 'brace',
    name: 'Brace',
    kind: 'guard',
    cost: 1,
    atk: 2,
    ward: 6,
    plus: { ward: 9 },
    tier: 'basic',
    source: 'basic',
    flavor: 'Plant your feet. Keep the light between you and it.',
    glyph: 'shield',
  }),
  card({
    id: ASH_ID,
    name: 'Ash',
    kind: 'curse',
    cost: 0,
    atk: 0,
    ward: 0,
    target: 'self',
    keywords: ['unplayable'],
    tier: 'special',
    source: 'curse',
    flavor: 'What is left of a hymn you should not have heard.',
    glyph: 'ash',
  }),
];

// ---------------------------------------------------------------------------
// The common pool: four cards for each affinity, and a few neutral ones
// ---------------------------------------------------------------------------

export const POOL: readonly CardDef[] = [
  // Sun
  card({ id: 'candle-oath', name: 'Candle Oath', kind: 'balanced', affinity: 'sun', cost: 1, atk: 5, ward: 4, plus: { atk: 7, ward: 5 }, tier: 'common', flavor: 'Sworn on a flame that has never once gone out.' }),
  card({ id: 'gilded-cut', name: 'Gilded Cut', kind: 'strike', affinity: 'sun', cost: 1, atk: 7, ward: 1, plus: { atk: 10 }, tier: 'common', flavor: 'Noonlight, folded into an edge.' }),
  card({
    id: 'halo-screen',
    name: 'Halo Screen',
    kind: 'guard',
    affinity: 'sun',
    cost: 1,
    atk: 2,
    ward: 9,
    effects: [{ type: 'heal', amount: 2 }],
    plus: { ward: 11, effects: [{ type: 'heal', amount: 4 }] },
    tier: 'uncommon',
    flavor: 'A ring of light that remembers what morning felt like.',
  }),
  card({
    id: 'unsetting',
    name: 'Unsetting',
    kind: 'strike',
    affinity: 'sun',
    target: 'allFoes',
    cost: 2,
    atk: 9,
    ward: 2,
    effects: [{ type: 'heal', amount: 4 }],
    plus: { atk: 12 },
    tier: 'rare',
    flavor: 'The sun that would not set, turned on the things that hide from it.',
  }),

  // Moon
  card({
    id: 'pale-needle',
    name: 'Pale Needle',
    kind: 'strike',
    affinity: 'moon',
    cost: 1,
    atk: 6,
    ward: 1,
    effects: [{ type: 'status', status: 'hex', stacks: 1 }],
    plus: { atk: 8 },
    tier: 'common',
    flavor: 'A sliver of the moon that used to rise.',
  }),
  card({ id: 'lidded-lamp', name: 'Lidded Lamp', kind: 'guard', affinity: 'moon', cost: 1, atk: 2, ward: 8, plus: { ward: 11 }, tier: 'common', flavor: 'Shut the light in. Let the dark break on the brass.' }),
  card({
    id: 'eclipse-seal',
    name: 'Eclipse Seal',
    kind: 'rite',
    affinity: 'moon',
    target: 'allFoes',
    cost: 1,
    atk: 0,
    ward: 3,
    effects: [{ type: 'status', status: 'hex', stacks: 1 }],
    plus: { effects: [{ type: 'status', status: 'hex', stacks: 2 }] },
    tier: 'uncommon',
    flavor: 'A circle drawn around every shadow in the room.',
  }),
  card({
    id: 'nocturne',
    name: 'Nocturne',
    kind: 'strike',
    affinity: 'moon',
    cost: 2,
    atk: 7,
    hits: 2,
    ward: 2,
    effects: [{ type: 'status', status: 'hex', stacks: 2 }],
    plus: { atk: 9 },
    tier: 'rare',
    flavor: 'Two notes, played in the dark, for someone who is not there.',
  }),

  // Flame
  card({
    id: 'cinder-flick',
    name: 'Cinder Flick',
    kind: 'strike',
    affinity: 'flame',
    cost: 0,
    atk: 3,
    ward: 0,
    effects: [{ type: 'status', status: 'burn', stacks: 2 }],
    keywords: ['fleeting'],
    plus: { atk: 4, effects: [{ type: 'status', status: 'burn', stacks: 3 }] },
    tier: 'common',
    flavor: 'Flicked from the wick. Gone before it lands.',
  }),
  card({
    id: 'pyre-brand',
    name: 'Pyre Brand',
    kind: 'strike',
    affinity: 'flame',
    cost: 1,
    atk: 5,
    ward: 2,
    effects: [{ type: 'status', status: 'burn', stacks: 2 }],
    plus: { atk: 6, effects: [{ type: 'status', status: 'burn', stacks: 3 }] },
    tier: 'common',
    flavor: 'The mark stays long after the iron is cold.',
  }),
  card({
    id: 'kiln-wall',
    name: 'Kiln Wall',
    kind: 'guard',
    affinity: 'flame',
    cost: 1,
    atk: 3,
    ward: 8,
    effects: [{ type: 'status', status: 'burn', stacks: 1 }],
    plus: { ward: 10 },
    tier: 'uncommon',
    flavor: 'Bricks that were fired in a noon that never ended.',
  }),
  card({
    id: 'immolation-rite',
    name: 'Immolation Rite',
    kind: 'rite',
    affinity: 'flame',
    target: 'allFoes',
    cost: 2,
    atk: 0,
    ward: 0,
    effects: [{ type: 'status', status: 'burn', stacks: 5 }],
    keywords: ['spent'],
    plus: { effects: [{ type: 'status', status: 'burn', stacks: 7 }] },
    tier: 'rare',
    flavor: 'Said once, in a room you intend to leave.',
  }),

  // Frost
  card({ id: 'rime-shard', name: 'Rime Shard', kind: 'strike', affinity: 'frost', cost: 1, atk: 6, ward: 2, plus: { atk: 9 }, tier: 'common', flavor: 'Broken off the night side and carried here in a glove.' }),
  card({ id: 'hoarfrost-mantle', name: 'Hoarfrost Mantle', kind: 'guard', affinity: 'frost', cost: 1, atk: 2, ward: 9, plus: { ward: 12 }, tier: 'common', flavor: 'Cold enough that the Fades think twice.' }),
  card({
    id: 'stillwater',
    name: 'Stillwater',
    kind: 'rite',
    affinity: 'frost',
    cost: 1,
    atk: 0,
    ward: 4,
    effects: [{ type: 'status', status: 'chill', stacks: 2 }],
    plus: { effects: [{ type: 'status', status: 'chill', stacks: 3 }] },
    tier: 'uncommon',
    flavor: 'Water that has not moved in a thousand years has opinions about hurrying.',
  }),
  card({
    id: 'glass-winter',
    name: 'Glass Winter',
    kind: 'strike',
    affinity: 'frost',
    target: 'allFoes',
    cost: 2,
    atk: 7,
    ward: 2,
    effects: [{ type: 'status', status: 'chill', stacks: 1 }],
    plus: { atk: 9 },
    tier: 'rare',
    flavor: 'Every window in the room frosts over at once.',
  }),

  // Gale
  card({
    id: 'loose-feather',
    name: 'Loose Feather',
    kind: 'strike',
    affinity: 'gale',
    cost: 0,
    atk: 2,
    hits: 2,
    ward: 0,
    keywords: ['fleeting'],
    plus: { atk: 3 },
    tier: 'common',
    flavor: 'Caught on an updraft that should not exist indoors.',
  }),
  card({
    id: 'weathervane',
    name: 'Weathervane',
    kind: 'balanced',
    affinity: 'gale',
    cost: 1,
    atk: 4,
    ward: 3,
    effects: [{ type: 'draw', count: 1 }],
    plus: { atk: 6 },
    tier: 'common',
    flavor: 'It spins toward whatever is coming.',
  }),
  card({ id: 'kite-string', name: 'Kite String', kind: 'strike', affinity: 'gale', cost: 1, atk: 3, hits: 3, ward: 1, plus: { atk: 4 }, tier: 'uncommon', flavor: 'Three cuts from one pull.' }),
  card({
    id: 'skirling-gale',
    name: 'Skirling Gale',
    kind: 'strike',
    affinity: 'gale',
    target: 'allFoes',
    cost: 2,
    atk: 4,
    hits: 2,
    ward: 1,
    effects: [{ type: 'draw', count: 1 }],
    plus: { atk: 5 },
    tier: 'rare',
    flavor: 'A wind that screams the names of doors it has slammed.',
  }),

  // Volt
  card({
    id: 'arc-tap',
    name: 'Arc Tap',
    kind: 'strike',
    affinity: 'volt',
    cost: 1,
    atk: 5,
    ward: 1,
    effects: [{ type: 'status', status: 'shock', stacks: 2 }],
    plus: { atk: 7 },
    tier: 'common',
    flavor: 'Touch the wire, then touch the Fade.',
  }),
  card({
    id: 'wire-fence',
    name: 'Wire Fence',
    kind: 'guard',
    affinity: 'volt',
    cost: 1,
    atk: 3,
    ward: 7,
    effects: [{ type: 'status', status: 'shock', stacks: 1 }],
    plus: { ward: 10 },
    tier: 'common',
    flavor: 'Strung between two dead streetlamps. Still humming.',
  }),
  card({
    id: 'galvanic-lance',
    name: 'Galvanic Lance',
    kind: 'strike',
    affinity: 'volt',
    cost: 2,
    atk: 12,
    ward: 1,
    effects: [{ type: 'status', status: 'shock', stacks: 3 }],
    keywords: ['pierce'],
    plus: { atk: 15 },
    tier: 'uncommon',
    flavor: 'Straight through ward, armour and whatever it thinks it is.',
  }),
  card({
    id: 'stormcall',
    name: 'Stormcall',
    kind: 'strike',
    affinity: 'volt',
    target: 'allFoes',
    cost: 2,
    atk: 5,
    hits: 2,
    ward: 1,
    effects: [{ type: 'status', status: 'shock', stacks: 2 }],
    plus: { atk: 6 },
    tier: 'rare',
    flavor: 'The weather the world had before it stopped.',
  }),

  // Neutral
  card({
    id: 'quick-breath',
    name: 'Quick Breath',
    kind: 'rite',
    target: 'self',
    cost: 0,
    atk: 0,
    ward: 0,
    effects: [{ type: 'draw', count: 1 }],
    keywords: ['fleeting'],
    plus: { effects: [{ type: 'draw', count: 2 }] },
    tier: 'common',
    flavor: 'In, out. Look again.',
  }),
  card({
    id: 'lamp-oil',
    name: 'Lamp Oil',
    kind: 'rite',
    target: 'self',
    cost: 0,
    atk: 0,
    ward: 1,
    effects: [{ type: 'light', amount: 2 }],
    keywords: ['spent'],
    plus: { effects: [{ type: 'light', amount: 3 }] },
    tier: 'uncommon',
    flavor: 'The good oil, from before. Save it for a bad night.',
  }),
  card({
    id: 'shatter-point',
    name: 'Shatter Point',
    kind: 'rite',
    cost: 1,
    atk: 2,
    ward: 2,
    effects: [{ type: 'crack', amount: 2 }],
    plus: { effects: [{ type: 'crack', amount: 3 }] },
    tier: 'uncommon',
    flavor: 'Every Shell has one. You only have to be patient.',
  }),
  card({
    id: 'vigil',
    name: 'Vigil',
    kind: 'guard',
    target: 'self',
    cost: 2,
    atk: 0,
    ward: 14,
    effects: [{ type: 'ward', amount: 8 }, { type: 'cleanse' }],
    keywords: ['steadfast'],
    plus: { ward: 18, effects: [{ type: 'ward', amount: 11 }, { type: 'cleanse' }] },
    tier: 'rare',
    flavor: 'Kept all night, by someone who has done it before.',
  }),
];

// ---------------------------------------------------------------------------
// Kindled cards. Same ids as the old Memory Cards, so collections carry over.
// ---------------------------------------------------------------------------

export const KINDLED: readonly CardDef[] = [
  card({
    id: 'card.anchor-shadow',
    name: "The Anchor's Shadow",
    kind: 'guard',
    affinity: 'moon',
    cost: 2,
    atk: 8,
    ward: 12,
    effects: [{ type: 'ward', amount: 8 }],
    keywords: ['steadfast'],
    plus: { ward: 15, effects: [{ type: 'ward', amount: 10 }] },
    tier: 'rare',
    source: 'kindling',
    stars: 5,
    flavor: "A rubbing of the Dominion's pillar. Its shadow is longer than it should be.",
    glyph: 'anchor',
  }),
  card({
    id: 'card.first-light',
    name: 'First Light, Framed',
    kind: 'rite',
    affinity: 'sun',
    target: 'self',
    cost: 0,
    atk: 0,
    ward: 3,
    effects: [
      { type: 'heal', amount: 6 },
      { type: 'light', amount: 2 },
      { type: 'gauge', amount: 25 },
    ],
    keywords: ['spent'],
    plus: {
      effects: [
        { type: 'heal', amount: 9 },
        { type: 'light', amount: 2 },
        { type: 'gauge', amount: 35 },
      ],
    },
    tier: 'rare',
    source: 'kindling',
    stars: 5,
    flavor: 'The only picture of a sunrise anyone on the Duskline has ever seen. It is warm to hold.',
    glyph: 'sun',
  }),
  card({
    id: 'card.ledger',
    name: "Lamplighter's Ledger",
    kind: 'balanced',
    cost: 1,
    atk: 6,
    ward: 4,
    effects: [{ type: 'draw', count: 1 }],
    keywords: ['linked'],
    plus: { atk: 8 },
    tier: 'uncommon',
    source: 'kindling',
    stars: 4,
    flavor: 'Every debt a Lamplighter has ever owed, in neat columns.',
    glyph: 'ledger',
  }),
  card({
    id: 'card.chime',
    name: 'Wind-Chime of Vesper',
    kind: 'rite',
    affinity: 'gale',
    target: 'self',
    cost: 0,
    atk: 0,
    ward: 2,
    effects: [
      { type: 'draw', count: 2 },
      { type: 'gauge', amount: 10 },
    ],
    keywords: ['spent'],
    plus: {
      effects: [
        { type: 'draw', count: 2 },
        { type: 'gauge', amount: 25 },
      ],
      keywords: [],
    },
    tier: 'uncommon',
    source: 'kindling',
    stars: 4,
    flavor: 'It rings whenever the crew is in trouble.',
    glyph: 'chime',
  }),
  card({
    id: 'card.ribbon',
    name: 'Ember Ribbon',
    kind: 'strike',
    affinity: 'flame',
    cost: 1,
    atk: 7,
    ward: 1,
    effects: [{ type: 'status', status: 'burn', stacks: 3 }],
    plus: { atk: 9, effects: [{ type: 'status', status: 'burn', stacks: 4 }] },
    tier: 'uncommon',
    source: 'kindling',
    stars: 4,
    flavor: 'Tied to a blade, it never quite stops glowing.',
    glyph: 'ribbon',
  }),
  card({
    id: 'card.key',
    name: "Warden's Key",
    kind: 'guard',
    cost: 1,
    atk: 3,
    ward: 7,
    effects: [{ type: 'crack', amount: 2 }],
    plus: { ward: 9, effects: [{ type: 'crack', amount: 3 }] },
    tier: 'uncommon',
    source: 'kindling',
    stars: 4,
    flavor: 'Opens a door that no longer exists, and every Shell that thinks it is one.',
    glyph: 'key',
  }),
  card({
    id: 'card.worn-lantern',
    name: 'Worn Lantern',
    kind: 'balanced',
    affinity: 'sun',
    cost: 1,
    atk: 5,
    ward: 5,
    effects: [{ type: 'heal', amount: 2 }],
    plus: { atk: 6, ward: 6 },
    tier: 'common',
    source: 'kindling',
    stars: 3,
    flavor: 'Dented, sooty, still warm.',
    glyph: 'lantern',
  }),
  card({
    id: 'card.patchwork-coat',
    name: 'Patchwork Coat',
    kind: 'guard',
    cost: 1,
    atk: 2,
    ward: 10,
    plus: { ward: 13 },
    tier: 'common',
    source: 'kindling',
    stars: 3,
    flavor: 'Every patch is from a different Turning.',
    glyph: 'coat',
  }),
  card({
    id: 'card.rusty-compass',
    name: 'Rusty Compass',
    kind: 'rite',
    affinity: 'gale',
    target: 'self',
    cost: 0,
    atk: 0,
    ward: 3,
    effects: [{ type: 'draw', count: 1 }],
    plus: { ward: 5 },
    tier: 'common',
    source: 'kindling',
    stars: 3,
    flavor: 'It points at whatever you were about to say.',
    glyph: 'compass',
  }),
  card({
    id: 'card.salt-biscuit',
    name: 'Salt Biscuit',
    kind: 'rite',
    target: 'self',
    cost: 1,
    atk: 0,
    ward: 3,
    effects: [{ type: 'heal', amount: 7 }],
    keywords: ['spent'],
    plus: { effects: [{ type: 'heal', amount: 10 }] },
    tier: 'common',
    source: 'kindling',
    stars: 3,
    flavor: 'Vesper ration. Hard as a hull plate. Surprisingly motivating.',
    glyph: 'biscuit',
  }),
  card({
    id: 'card.tin-whistle',
    name: 'Tin Whistle',
    kind: 'strike',
    affinity: 'volt',
    cost: 0,
    atk: 3,
    ward: 1,
    effects: [{ type: 'status', status: 'shock', stacks: 3 }],
    plus: { atk: 4, effects: [{ type: 'status', status: 'shock', stacks: 4 }] },
    tier: 'common',
    source: 'kindling',
    stars: 3,
    flavor: 'One shrill note, and the Fade flinches.',
    glyph: 'whistle',
  }),
];

// ---------------------------------------------------------------------------
// Bound Fades: after a win, a Fade you fought can be pinned to paper.
// ---------------------------------------------------------------------------

export const BOUND: readonly CardDef[] = [
  card({
    id: 'bound.wisp',
    name: 'Bound Wisp',
    kind: 'strike',
    affinity: 'flame',
    cost: 1,
    atk: 4,
    ward: 1,
    effects: [{ type: 'status', status: 'burn', stacks: 3 }],
    plus: { effects: [{ type: 'status', status: 'burn', stacks: 5 }] },
    tier: 'common',
    source: 'bound',
    flavor: 'It still flickers when you are angry.',
    glyph: 'fade:wisp',
  }),
  card({ id: 'bound.hound', name: 'Bound Hound', kind: 'strike', cost: 1, atk: 3, hits: 2, ward: 2, plus: { atk: 4, hits: 2 }, tier: 'common', source: 'bound', flavor: 'Loyal to whoever holds the paper.', glyph: 'fade:hound' }),
  card({
    id: 'bound.moth',
    name: 'Bound Moth',
    kind: 'rite',
    affinity: 'gale',
    target: 'self',
    cost: 0,
    atk: 0,
    ward: 0,
    effects: [
      { type: 'draw', count: 1 },
      { type: 'gauge', amount: 10 },
    ],
    keywords: ['fleeting'],
    plus: {
      effects: [
        { type: 'draw', count: 1 },
        { type: 'gauge', amount: 20 },
      ],
      keywords: [],
    },
    tier: 'common',
    source: 'bound',
    flavor: 'It flies toward the next card like it is a lamp.',
    glyph: 'fade:moth',
  }),
  card({ id: 'bound.acolyte', name: 'Bound Acolyte', kind: 'balanced', affinity: 'sun', cost: 1, atk: 5, ward: 5, plus: { atk: 7, ward: 6 }, tier: 'common', source: 'bound', flavor: 'It prays to you now. You would rather it did not.', glyph: 'fade:acolyte' }),
  card({
    id: 'bound.wraith',
    name: 'Bound Wraith',
    kind: 'rite',
    affinity: 'moon',
    cost: 1,
    atk: 2,
    ward: 4,
    effects: [{ type: 'status', status: 'hex', stacks: 2 }],
    plus: { effects: [{ type: 'status', status: 'hex', stacks: 3 }] },
    tier: 'common',
    source: 'bound',
    flavor: 'Its cold hand, now on someone else’s shoulder.',
    glyph: 'fade:wraith',
  }),
  card({
    id: 'bound.choir',
    name: 'Bound Choir',
    kind: 'rite',
    affinity: 'frost',
    target: 'allFoes',
    cost: 1,
    atk: 2,
    ward: 3,
    effects: [{ type: 'status', status: 'chill', stacks: 1 }],
    plus: { atk: 3, effects: [{ type: 'status', status: 'chill', stacks: 2 }] },
    tier: 'uncommon',
    source: 'bound',
    flavor: 'A hymn that makes the room colder by one voice.',
    glyph: 'fade:choir',
  }),
  card({ id: 'bound.husk', name: 'Bound Husk', kind: 'guard', cost: 1, atk: 2, ward: 11, plus: { ward: 14 }, tier: 'uncommon', source: 'bound', flavor: 'A door that only opens for you.', glyph: 'fade:husk' }),
  card({
    id: 'bound.static',
    name: 'Bound Static',
    kind: 'strike',
    affinity: 'volt',
    cost: 2,
    atk: 9,
    ward: 2,
    effects: [{ type: 'status', status: 'shock', stacks: 4 }],
    keywords: ['pierce'],
    plus: { atk: 12 },
    tier: 'uncommon',
    source: 'bound',
    flavor: 'Its lance, and some of its temper.',
    glyph: 'fade:static',
  }),
  card({
    id: 'bound.warden',
    name: 'Bound Warden',
    kind: 'guard',
    affinity: 'moon',
    cost: 2,
    atk: 6,
    ward: 14,
    effects: [{ type: 'status', status: 'hex', stacks: 1 }],
    keywords: ['steadfast'],
    plus: { ward: 18 },
    tier: 'rare',
    source: 'bound',
    flavor: 'It kept the Root for a thousand years. It keeps you now.',
    glyph: 'fade:warden',
  }),
  card({
    id: 'bound.bell',
    name: 'Bound Bell',
    kind: 'strike',
    affinity: 'volt',
    target: 'allFoes',
    cost: 2,
    atk: 8,
    ward: 3,
    effects: [{ type: 'status', status: 'chill', stacks: 1 }],
    plus: { atk: 11 },
    tier: 'rare',
    source: 'bound',
    flavor: 'It will toll once more, for you, when you ask.',
    glyph: 'fade:bell',
  }),
  card({
    id: 'bound.keeper',
    name: 'Bound Hour',
    kind: 'rite',
    target: 'self',
    cost: 1,
    atk: 0,
    ward: 4,
    effects: [
      { type: 'light', amount: 2 },
      { type: 'draw', count: 2 },
    ],
    keywords: ['spent'],
    plus: { cost: 0 },
    tier: 'rare',
    source: 'bound',
    flavor: 'One hour, taken from the one who kept them all.',
    glyph: 'fade:keeper',
  }),
];
