import type { EnemyDef } from '@duskline/core';
import { foeSkill } from './helpers';

/**
 * The Fades: memories that lost their person, pouring out of the Hush as paper-cut silhouettes
 * with static at the edges. Each family is weak to two affinities, so a party has to bring the
 * right mix to Break them.
 */
export const ENEMIES: readonly EnemyDef[] = [
  {
    id: 'wisp',
    name: 'Fade Wisp',
    family: 'wisp',
    tier: 'mob',
    base: { hp: 690, atk: 210, def: 24, spd: 118 },
    shell: 3,
    weaknesses: ['sun', 'gale'],
    resists: ['moon'],
    foeKit: [
      foeSkill({ id: 'wisp.nip', name: 'Static Nip', power: 0.9, blurb: 'A quick, stinging bite.' }),
      foeSkill({
        id: 'wisp.flicker',
        name: 'Flicker',
        power: 0.6,
        blurb: 'A stutter of light that slows the target.',
        effects: [{ type: 'delay', on: 'targets', pct: 0.08 }],
      }),
    ],
    ai: { weights: { 'wisp.nip': 3, 'wisp.flicker': 1 } },
    blurb: 'A scrap of a memory, too small to remember whose.',
    scale: 0.8,
  },
  {
    id: 'hound',
    name: 'Fade Hound',
    family: 'hound',
    tier: 'mob',
    base: { hp: 1000, atk: 340, def: 30, spd: 112 },
    shell: 4,
    weaknesses: ['volt', 'flame'],
    resists: [],
    foeKit: [
      foeSkill({ id: 'hound.snap', name: 'Snap', power: 0.8, blurb: 'A fast snap at the heels.' }),
      foeSkill({ id: 'hound.pounce', name: 'Pounce', power: 1.4, blurb: 'A full-weight leap.' }),
    ],
    ai: { pattern: ['hound.snap', 'hound.snap', 'hound.pounce'], focus: 'lowestHp' },
    blurb: 'Someone’s loyal dog, remembered so hard it stayed.',
    scale: 1.0,
  },
  {
    id: 'wraith',
    name: 'Fade Wraith',
    family: 'wraith',
    tier: 'mob',
    base: { hp: 1020, atk: 240, def: 34, spd: 100 },
    shell: 4,
    weaknesses: ['sun', 'frost'],
    resists: ['gale'],
    foeKit: [
      foeSkill({ id: 'wraith.touch', name: 'Drain Touch', power: 1.0, blurb: 'A cold hand on the shoulder.' }),
      foeSkill({
        id: 'wraith.wail',
        name: 'Wail',
        target: 'allEnemies',
        power: 0.5,
        blurb: 'A thin cry that loosens everyone’s guard.',
        effects: [{ type: 'mod', on: 'foes', stat: 'def', pct: -0.1, turns: 2 }],
      }),
    ],
    ai: { weights: { 'wraith.touch': 2, 'wraith.wail': 1 } },
    blurb: 'A person-shaped absence, still asking for directions.',
    scale: 1.15,
  },
  {
    id: 'husk',
    name: 'Fade Husk',
    family: 'husk',
    tier: 'mob',
    base: { hp: 2800, atk: 380, def: 60, spd: 88 },
    shell: 6,
    weaknesses: ['flame', 'moon'],
    resists: ['frost'],
    foeKit: [
      foeSkill({ id: 'husk.slam', name: 'Slam', power: 1.3, blurb: 'Swings a door like a club.' }),
      foeSkill({
        id: 'husk.brace',
        name: 'Brace',
        target: 'self',
        power: 0,
        blurb: 'Locks itself up tight: DEF up for 2 turns.',
        effects: [{ type: 'mod', on: 'self', stat: 'def', pct: 0.4, turns: 2 }],
      }),
      foeSkill({ id: 'husk.crush', name: 'Crush', power: 2.6, heavy: true, blurb: 'Brings the whole house down on one target.' }),
    ],
    ai: { pattern: ['husk.slam', 'husk.brace', 'husk.crush'], focus: 'highestAtk' },
    blurb: 'Built from a hundred lost coats and someone’s front door.',
    scale: 1.45,
  },
  {
    id: 'choir',
    name: 'Fade Choir',
    family: 'choir',
    tier: 'mob',
    base: { hp: 1100, atk: 220, def: 30, spd: 104 },
    shell: 4,
    weaknesses: ['volt', 'moon'],
    resists: ['sun'],
    foeKit: [
      foeSkill({
        id: 'choir.hymn',
        name: 'Hymn',
        target: 'allAllies',
        power: 0,
        blurb: 'A hollow hymn that mends every Fade nearby.',
        effects: [{ type: 'heal', on: 'party', of: 'maxHp', scale: 0.12 }],
      }),
      foeSkill({
        id: 'choir.discord',
        name: 'Discord',
        power: 0.8,
        blurb: 'A sour note that strips DEF.',
        effects: [{ type: 'mod', on: 'targets', stat: 'def', pct: -0.2, turns: 2 }],
      }),
    ],
    ai: { pattern: ['choir.hymn', 'choir.discord'] },
    blurb: 'Six voices, none of them sure of the tune.',
    scale: 1.1,
  },
  {
    id: 'static',
    name: 'Static Knight',
    family: 'static',
    tier: 'elite',
    base: { hp: 2600, atk: 380, def: 48, spd: 106 },
    shell: 7,
    weaknesses: ['gale', 'volt'],
    resists: ['sun'],
    foeKit: [
      foeSkill({ id: 'static.arc', name: 'Arc', power: 1.1, blurb: 'A lash of white noise.' }),
      foeSkill({ id: 'static.whiteout', name: 'Whiteout', target: 'allEnemies', power: 1.2, heavy: true, blurb: 'The whole field washes out.' }),
    ],
    ai: { pattern: ['static.arc', 'static.arc', 'static.whiteout'], focus: 'lowestHp' },
    blurb: 'A soldier from a signal that never stopped broadcasting.',
    scale: 1.4,
  },
  {
    id: 'warden',
    name: 'The Umbral Warden',
    family: 'warden',
    tier: 'boss',
    base: { hp: 3000, atk: 470, def: 55, spd: 96 },
    shell: 8,
    weaknesses: ['sun', 'moon'],
    resists: ['frost'],
    foeKit: [
      foeSkill({ id: 'warden.strike', name: 'Eclipse Strike', power: 1.4, blurb: 'A cut from a darkened sun.' }),
      foeSkill({
        id: 'warden.chorus',
        name: 'Hollow Chorus',
        target: 'allEnemies',
        power: 0.9,
        blurb: 'Every lost voice at once: ATK down for 2 turns.',
        effects: [{ type: 'mod', on: 'foes', stat: 'atk', pct: -0.15, turns: 2 }],
      }),
      foeSkill({ id: 'warden.unwritten', name: 'The Unwritten', power: 2.6, heavy: true, blurb: 'Erases one target from the page.' }),
    ],
    ai: { pattern: ['warden.strike', 'warden.chorus', 'warden.strike', 'warden.unwritten'], focus: 'highestAtk' },
    blurb: 'A keeper of records who forgot everything but the keeping.',
    scale: 1.8,
  },
];
