import type { FoeDef } from '@duskline/core';

/**
 * The Fades: shadows of everything that was on the night side when the world stopped, torn loose
 * and pouring out of the Gnomon. Paper-cut silhouettes with static at the edges. Each family is
 * weak to two affinities, and each tells you what it will do next.
 *
 * Numbers are for the Root. Deeper strata and higher floors scale HP and power up.
 */
export const FOES: readonly FoeDef[] = [
  {
    id: 'wisp',
    name: 'Candle Wisp',
    family: 'wisp',
    tier: 'mob',
    hp: 18,
    shell: 2,
    weaknesses: ['sun', 'gale'],
    resists: ['flame'],
    moves: [
      { id: 'flicker', name: 'Flicker', dmg: 5 },
      { id: 'gutter', name: 'Gutter', dmg: 3, afflict: { status: 'dim', stacks: 1 } },
    ],
    weights: { flicker: 2, gutter: 1 },
    blurb: 'A scrap of a memory, burning at both ends.',
    scale: 0.8,
    bind: 'bound.wisp',
  },
  {
    id: 'hound',
    name: 'Hush Hound',
    family: 'hound',
    tier: 'mob',
    hp: 22,
    shell: 2,
    weaknesses: ['volt', 'flame'],
    resists: [],
    moves: [
      { id: 'snap', name: 'Snap', dmg: 3, hits: 2 },
      { id: 'pounce', name: 'Pounce', dmg: 9 },
    ],
    pattern: ['snap', 'snap', 'pounce'],
    blurb: 'Someone’s loyal dog, remembered so hard it stayed.',
    scale: 1,
    bind: 'bound.hound',
  },
  {
    id: 'moth',
    name: 'Lamp Moth',
    family: 'moth',
    tier: 'mob',
    hp: 13,
    shell: 1,
    weaknesses: ['flame', 'gale'],
    resists: [],
    moves: [
      { id: 'drink', name: 'Drink the Light', dmg: 3, afflict: { status: 'dim', stacks: 1 } },
      { id: 'flutter', name: 'Flutter', dmg: 4 },
    ],
    weights: { drink: 1, flutter: 2 },
    blurb: 'It is drawn to your lamp. It wants what is inside.',
    scale: 0.7,
    bind: 'bound.moth',
  },
  {
    id: 'acolyte',
    name: 'Unturning Acolyte',
    family: 'acolyte',
    tier: 'mob',
    hp: 22,
    shell: 2,
    weaknesses: ['sun', 'volt'],
    resists: [],
    moves: [
      { id: 'knife', name: 'Ritual Knife', dmg: 6 },
      { id: 'rite', name: 'Rite of Stillness', wardAll: 4 },
      { id: 'ash', name: 'Ash Hymn', dmg: 3, curse: 1 },
    ],
    pattern: ['knife', 'rite', 'ash'],
    blurb: 'A cultist of the Unturning. It prays that nothing will ever change again.',
    scale: 0.95,
    bind: 'bound.acolyte',
  },
  {
    id: 'wraith',
    name: 'Veil Wraith',
    family: 'wraith',
    tier: 'mob',
    hp: 26,
    shell: 3,
    weaknesses: ['sun', 'frost'],
    resists: ['gale'],
    moves: [
      { id: 'touch', name: 'Cold Touch', dmg: 5, afflict: { status: 'hex', stacks: 2 } },
      { id: 'wail', name: 'Wail', dmg: 7 },
    ],
    pattern: ['touch', 'wail'],
    blurb: 'A hooded shape that was once somebody’s grief.',
    scale: 1.05,
    bind: 'bound.wraith',
  },
  {
    id: 'choir',
    name: 'Paper Choir',
    family: 'choir',
    tier: 'mob',
    hp: 24,
    shell: 3,
    weaknesses: ['volt', 'moon'],
    resists: [],
    moves: [
      { id: 'chorus', name: 'Cold Chorus', dmg: 3, hits: 2, afflict: { status: 'chill', stacks: 1 } },
      { id: 'hymn', name: 'Mending Hymn', healAll: 4 },
    ],
    pattern: ['chorus', 'hymn'],
    blurb: 'A bell of paper singers, folded out of a hymnal nobody reads.',
    scale: 1.1,
    bind: 'bound.choir',
  },
  {
    id: 'husk',
    name: 'Door Husk',
    family: 'husk',
    tier: 'elite',
    hp: 55,
    shell: 4,
    weaknesses: ['flame', 'moon'],
    resists: [],
    moves: [
      { id: 'rend', name: 'Rend', dmg: 7, shatter: true },
      { id: 'brace', name: 'Bar the Door', ward: 12, rage: 1 },
      { id: 'slam', name: 'Slam', dmg: 12 },
    ],
    pattern: ['rend', 'brace', 'slam'],
    blurb: 'A door that walked out of its frame, wearing every coat that ever hung on it.',
    scale: 1.25,
    bind: 'bound.husk',
  },
  {
    id: 'static',
    name: 'Static Knight',
    family: 'static',
    tier: 'elite',
    hp: 54,
    shell: 5,
    weaknesses: ['frost', 'gale'],
    resists: [],
    moves: [
      { id: 'arc', name: 'Arc', dmg: 3, hits: 3 },
      { id: 'guard', name: 'Shield Wall', ward: 12 },
      { id: 'lance', name: 'Lance', dmg: 11, pierce: true },
    ],
    pattern: ['arc', 'guard', 'lance'],
    blurb: 'Armour with nobody in it, humming at the frequency of a dead city.',
    scale: 1.3,
    bind: 'bound.static',
  },
  {
    id: 'warden',
    name: 'The Warden',
    family: 'warden',
    tier: 'boss',
    hp: 150,
    shell: 6,
    weaknesses: ['sun', 'frost'],
    resists: [],
    moves: [
      { id: 'page', name: 'Turn the Page', dmg: 5, hits: 2, afflict: { status: 'hex', stacks: 1 } },
      { id: 'toll', name: 'Toll', dmg: 10 },
      { id: 'call', name: 'Call the Moths', summon: 'moth', ward: 8 },
      { id: 'litany', name: 'Litany', wardAll: 10, rage: 2 },
      { id: 'verdict', name: 'Verdict', dmg: 18 },
    ],
    pattern: ['page', 'toll', 'call', 'litany', 'verdict'],
    blurb: 'Keeper of the Root. A robed thing with a page for a halo, reading the names of the Stilled.',
    scale: 1.5,
    bind: 'bound.warden',
  },
  {
    id: 'bell',
    name: 'The Tolling Bell',
    family: 'bell',
    tier: 'boss',
    hp: 160,
    shell: 7,
    weaknesses: ['volt', 'moon'],
    resists: ['sun'],
    moves: [
      { id: 'toll', name: 'Double Toll', dmg: 6, hits: 2 },
      { id: 'drone', name: 'Drone', dmg: 5, afflict: { status: 'chill', stacks: 2 } },
      { id: 'call', name: 'Call the Choir', summon: 'choir' },
      { id: 'silence', name: 'Silence', curse: 2, ward: 14 },
      { id: 'peal', name: 'Great Peal', dmg: 18 },
    ],
    pattern: ['toll', 'drone', 'call', 'silence', 'peal'],
    blurb: 'The bell of the Hollow, with one eye where the clapper should be. Every toll stops a heart for a moment.',
    scale: 1.6,
    bind: 'bound.bell',
  },
  {
    id: 'keeper',
    name: 'The Hour-Keeper',
    family: 'keeper',
    tier: 'boss',
    hp: 190,
    shell: 8,
    weaknesses: ['sun', 'gale'],
    resists: [],
    moves: [
      { id: 'hands', name: 'Clock Hands', dmg: 8, hits: 2 },
      { id: 'stop', name: 'Stop', afflict: { status: 'dim', stacks: 2 }, ward: 16 },
      { id: 'shear', name: 'Shear', dmg: 10, shatter: true },
      { id: 'call', name: 'Call the Faithful', summon: 'acolyte' },
      { id: 'hour', name: 'Keep the Hour', rage: 3, heal: 20 },
      { id: 'midnight', name: 'Midnight', dmg: 22 },
    ],
    pattern: ['hands', 'stop', 'shear', 'call', 'hour', 'midnight'],
    blurb: 'High priest of the Unturning, at the top of the Gnomon. It holds the shadow in place with both hands.',
    scale: 1.7,
    bind: 'bound.keeper',
  },
];
