import type { CardDef, HeroDef } from '@duskline/core';
import { card } from './helpers';

/**
 * The Lamplighters. Six story heroes join through the climb for free; six Afterlights, people
 * from earlier Turnings, come from Kindling. Every hero climbs alone with a deck of their own:
 * three Lamp Cuts, three Braces, two copies of their signature card. Two more signature cards
 * turn up only in their rewards, and the ultimate is conjured when their gauge fills.
 */

const STARTER = (sig: string): string[] => ['cut', 'cut', 'cut', 'brace', 'brace', 'brace', sig, sig];

// ---------------------------------------------------------------------------
// Hero cards
// ---------------------------------------------------------------------------

export const HERO_CARDS: readonly CardDef[] = [
  // Wren: sun, heals as she fights.
  card({ id: 'wren.swing', name: 'Lantern Swing', kind: 'balanced', affinity: 'sun', cost: 1, atk: 6, ward: 3, effects: [{ type: 'heal', amount: 2 }], plus: { atk: 7, effects: [{ type: 'heal', amount: 3 }] }, tier: 'basic', source: 'hero', hero: 'wren', flavor: 'Hold the light steady. Everything else can shake.', glyph: 'prop:lantern' }),
  card({ id: 'wren.rekindle', name: 'Rekindle', kind: 'rite', affinity: 'sun', target: 'self', cost: 1, atk: 0, ward: 2, effects: [{ type: 'heal', amount: 5 }, { type: 'light', amount: 1 }], plus: { effects: [{ type: 'heal', amount: 7 }, { type: 'light', amount: 1 }] }, tier: 'uncommon', source: 'hero', hero: 'wren', flavor: 'Blow on the coal. It remembers being a fire.', glyph: 'prop:lantern' }),
  card({ id: 'wren.vigil', name: 'Dawn Vigil', kind: 'guard', affinity: 'sun', cost: 2, atk: 4, ward: 13, effects: [{ type: 'heal', amount: 4 }], plus: { ward: 16 }, tier: 'rare', source: 'hero', hero: 'wren', flavor: 'She kept the lamp lit until someone came. Someone always came.', glyph: 'prop:lantern' }),
  card({ id: 'wren.ult', name: 'Dawn Toll', kind: 'strike', affinity: 'sun', target: 'allFoes', cost: 0, atk: 10, ward: 0, effects: [{ type: 'heal', amount: 8 }], keywords: ['fleeting'], plus: { atk: 14, effects: [{ type: 'heal', amount: 12 }] }, tier: 'special', source: 'ultimate', hero: 'wren', flavor: 'A bell of borrowed morning.', glyph: 'hero:wren' }),

  // Io: moon, hits hard, from a time when the world still turned.
  card({ id: 'io.cut', name: 'Moon Cut', kind: 'strike', affinity: 'moon', cost: 1, atk: 7, ward: 1, plus: { atk: 10 }, tier: 'basic', source: 'hero', hero: 'io', flavor: 'A crescent, drawn quickly.', glyph: 'prop:blade' }),
  card({ id: 'io.turning', name: 'Old Turning', kind: 'strike', affinity: 'moon', cost: 2, atk: 15, ward: 1, effects: [{ type: 'status', status: 'hex', stacks: 1 }], plus: { atk: 19 }, tier: 'uncommon', source: 'hero', hero: 'io', flavor: 'A cut from an age that no longer exists.', glyph: 'prop:blade' }),
  card({ id: 'io.lidless', name: 'Lidless Hour', kind: 'strike', affinity: 'moon', cost: 1, atk: 5, hits: 3, ward: 0, keywords: ['fleeting'], plus: { atk: 6 }, tier: 'rare', source: 'hero', hero: 'io', flavor: 'Three strokes in the time it takes a stopped clock to tick.', glyph: 'prop:blade' }),
  card({ id: 'io.ult', name: 'First Turning', kind: 'strike', affinity: 'moon', cost: 0, atk: 30, ward: 0, effects: [{ type: 'crack', amount: 2 }], keywords: ['fleeting'], plus: { atk: 40 }, tier: 'special', source: 'ultimate', hero: 'io', flavor: 'The world turns once, just for her.', glyph: 'hero:io' }),

  // Marisol: volt, a wall with a temper.
  card({ id: 'marisol.jab', name: 'Rail Jab', kind: 'balanced', affinity: 'volt', cost: 1, atk: 5, ward: 5, effects: [{ type: 'status', status: 'shock', stacks: 2 }], plus: { atk: 5, ward: 6, effects: [{ type: 'status', status: 'shock', stacks: 3 }] }, tier: 'basic', source: 'hero', hero: 'marisol', flavor: 'A short, mean jab with the deck rail.', glyph: 'prop:rail' }),
  card({ id: 'marisol.ward', name: 'Storm Ward', kind: 'guard', affinity: 'volt', cost: 1, atk: 3, ward: 9, effects: [{ type: 'ward', amount: 4 }], plus: { ward: 11, effects: [{ type: 'ward', amount: 6 }] }, tier: 'uncommon', source: 'hero', hero: 'marisol', flavor: 'The air crackles. Nothing comes closer.', glyph: 'prop:rail' }),
  card({ id: 'marisol.anchor', name: 'Anchor Drop', kind: 'strike', affinity: 'volt', target: 'allFoes', cost: 2, atk: 9, ward: 2, effects: [{ type: 'status', status: 'shock', stacks: 3 }], plus: { atk: 12 }, tier: 'rare', source: 'hero', hero: 'marisol', flavor: 'The Strider’s anchor, dropped on the whole stair.', glyph: 'prop:rail' }),
  card({ id: 'marisol.ult', name: 'Thunder Anchor', kind: 'strike', affinity: 'volt', target: 'allFoes', cost: 0, atk: 10, ward: 0, effects: [{ type: 'ward', amount: 12 }, { type: 'status', status: 'shock', stacks: 3 }], keywords: ['fleeting'], plus: { atk: 13 }, tier: 'special', source: 'ultimate', hero: 'marisol', flavor: 'Nobody gets left behind on my deck.', glyph: 'hero:marisol' }),

  // Tamsin: frost, slows and exposes.
  card({ id: 'tamsin.needle', name: 'Star Needle', kind: 'strike', affinity: 'frost', cost: 1, atk: 3, hits: 2, ward: 2, plus: { atk: 4 }, tier: 'basic', source: 'hero', hero: 'tamsin', flavor: 'Thrown slivers of starlight ice.', glyph: 'prop:needle' }),
  card({ id: 'tamsin.bind', name: 'Constellation Bind', kind: 'rite', affinity: 'frost', cost: 1, atk: 0, ward: 3, effects: [{ type: 'status', status: 'chill', stacks: 2 }, { type: 'status', status: 'hex', stacks: 1 }], plus: { effects: [{ type: 'status', status: 'chill', stacks: 2 }, { type: 'status', status: 'hex', stacks: 2 }] }, tier: 'uncommon', source: 'hero', hero: 'tamsin', flavor: 'Pinned to a sky that stopped moving.', glyph: 'prop:needle' }),
  card({ id: 'tamsin.night', name: 'Long Night', kind: 'strike', affinity: 'frost', target: 'allFoes', cost: 2, atk: 6, ward: 2, effects: [{ type: 'status', status: 'chill', stacks: 1 }, { type: 'status', status: 'hex', stacks: 1 }], plus: { atk: 8 }, tier: 'rare', source: 'hero', hero: 'tamsin', flavor: 'Night falls on the field, and does not lift.', glyph: 'prop:needle' }),
  card({ id: 'tamsin.ult', name: 'The Stars Remember', kind: 'strike', affinity: 'frost', target: 'allFoes', cost: 0, atk: 8, ward: 0, effects: [{ type: 'status', status: 'chill', stacks: 2 }, { type: 'status', status: 'hex', stacks: 2 }], keywords: ['fleeting'], plus: { atk: 11 }, tier: 'special', source: 'ultimate', hero: 'tamsin', flavor: 'The sky moved once. Her skin remembers.', glyph: 'hero:tamsin' }),

  // Aurelian: flame, opens every turn with a formal, brutal cut.
  card({ id: 'aurelian.blade', name: 'Dominion Blade', kind: 'strike', affinity: 'flame', cost: 1, atk: 5, ward: 1, effects: [{ type: 'status', status: 'burn', stacks: 2 }], plus: { atk: 8, effects: [{ type: 'status', status: 'burn', stacks: 3 }] }, tier: 'basic', source: 'hero', hero: 'aurelian', flavor: 'A clean, formal cut.', glyph: 'prop:greatsword' }),
  card({ id: 'aurelian.cleave', name: 'Solar Cleave', kind: 'strike', affinity: 'flame', target: 'allFoes', cost: 2, atk: 8, ward: 1, effects: [{ type: 'status', status: 'burn', stacks: 2 }], plus: { atk: 11 }, tier: 'uncommon', source: 'hero', hero: 'aurelian', flavor: 'A wide arc of noon fire.', glyph: 'prop:greatsword' }),
  card({ id: 'aurelian.verdict', name: 'Meridian Verdict', kind: 'strike', affinity: 'flame', cost: 3, atk: 26, ward: 0, plus: { atk: 34 }, tier: 'rare', source: 'hero', hero: 'aurelian', flavor: 'The Dominion’s final ruling.', glyph: 'prop:greatsword' }),
  card({ id: 'aurelian.ult', name: 'Noon Judgement', kind: 'strike', affinity: 'flame', cost: 0, atk: 24, ward: 0, effects: [{ type: 'status', status: 'burn', stacks: 6 }], keywords: ['fleeting'], plus: { atk: 32 }, tier: 'special', source: 'ultimate', hero: 'aurelian', flavor: 'Mercy should not look like this.', glyph: 'hero:aurelian' }),

  // Pip: gale, patches things up and keeps the hand moving.
  card({ id: 'pip.snap', name: 'Kite Snap', kind: 'balanced', affinity: 'gale', cost: 1, atk: 4, ward: 2, effects: [{ type: 'draw', count: 1 }], plus: { atk: 6, ward: 3 }, tier: 'basic', source: 'hero', hero: 'pip', flavor: 'The clockwork kite snaps, and comes back with something.', glyph: 'prop:kite' }),
  card({ id: 'pip.patch', name: 'Windfall Patch', kind: 'rite', affinity: 'gale', target: 'self', cost: 1, atk: 0, ward: 2, effects: [{ type: 'heal', amount: 6 }, { type: 'draw', count: 1 }], plus: { effects: [{ type: 'heal', amount: 9 }, { type: 'draw', count: 1 }] }, tier: 'uncommon', source: 'hero', hero: 'pip', flavor: 'If it’s broken, I can fix it.', glyph: 'prop:kite' }),
  card({ id: 'pip.gale', name: 'Clockwork Gale', kind: 'strike', affinity: 'gale', target: 'allFoes', cost: 1, atk: 3, hits: 2, ward: 0, keywords: ['fleeting'], plus: { atk: 4 }, tier: 'rare', source: 'hero', hero: 'pip', flavor: 'Wind-up weather.', glyph: 'prop:kite' }),
  card({ id: 'pip.ult', name: 'Clockwork Tempest', kind: 'strike', affinity: 'gale', target: 'allFoes', cost: 0, atk: 5, hits: 3, ward: 0, effects: [{ type: 'heal', amount: 6 }], keywords: ['fleeting'], plus: { atk: 7 }, tier: 'special', source: 'ultimate', hero: 'pip', flavor: 'If it’s not broken, I can improve it until it is.', glyph: 'hero:pip' }),

  // Ysolde: frost, a tide wall.
  card({ id: 'ysolde.buoy', name: 'Buoy Strike', kind: 'balanced', affinity: 'frost', cost: 1, atk: 5, ward: 6, effects: [{ type: 'status', status: 'chill', stacks: 1 }], plus: { atk: 7, ward: 8 }, tier: 'basic', source: 'hero', hero: 'ysolde', flavor: 'The old lantern-buoy, swung like a flail.', glyph: 'prop:lantern' }),
  card({ id: 'ysolde.tidewall', name: 'Tidewall', kind: 'guard', affinity: 'frost', cost: 1, atk: 2, ward: 10, effects: [{ type: 'ward', amount: 4 }], keywords: ['steadfast'], plus: { ward: 13 }, tier: 'uncommon', source: 'hero', hero: 'ysolde', flavor: 'A wall of cold water, standing up out of nowhere.', glyph: 'prop:lantern' }),
  card({ id: 'ysolde.undertow', name: 'Undertow', kind: 'strike', affinity: 'frost', cost: 2, atk: 12, ward: 3, effects: [{ type: 'status', status: 'chill', stacks: 2 }], plus: { atk: 16 }, tier: 'rare', source: 'hero', hero: 'ysolde', flavor: 'The sea forgot how to move. She did not.', glyph: 'prop:lantern' }),
  card({ id: 'ysolde.ult', name: 'Drowned Lantern', kind: 'strike', affinity: 'frost', target: 'allFoes', cost: 0, atk: 9, ward: 0, effects: [{ type: 'ward', amount: 14 }, { type: 'status', status: 'chill', stacks: 1 }], keywords: ['fleeting'], plus: { atk: 12 }, tier: 'special', source: 'ultimate', hero: 'ysolde', flavor: 'A lantern from the bottom of a forgotten sea.', glyph: 'hero:ysolde' }),

  // Kestrel: gale, finds the crack in everything.
  card({ id: 'kestrel.cut', name: 'Compass Cut', kind: 'strike', affinity: 'gale', cost: 1, atk: 4, hits: 2, ward: 1, plus: { atk: 5 }, tier: 'basic', source: 'hero', hero: 'kestrel', flavor: 'Precise, fast, and then again.', glyph: 'prop:compass' }),
  card({ id: 'kestrel.bearing', name: 'Bearing Shot', kind: 'strike', affinity: 'gale', cost: 1, atk: 7, ward: 1, effects: [{ type: 'crack', amount: 1 }], keywords: ['pierce'], plus: { atk: 9 }, tier: 'uncommon', source: 'hero', hero: 'kestrel', flavor: 'A pinpoint shot on a line only she can see.', glyph: 'prop:compass' }),
  card({ id: 'kestrel.roads', name: 'Every Road North', kind: 'strike', affinity: 'gale', cost: 2, atk: 4, hits: 4, ward: 1, plus: { atk: 5 }, tier: 'rare', source: 'hero', hero: 'kestrel', flavor: 'Every line on her map points at the enemy.', glyph: 'prop:compass' }),
  card({ id: 'kestrel.ult', name: 'True North', kind: 'strike', affinity: 'gale', cost: 0, atk: 8, hits: 3, ward: 0, effects: [{ type: 'crack', amount: 3 }], keywords: ['fleeting', 'pierce'], plus: { atk: 10 }, tier: 'special', source: 'ultimate', hero: 'kestrel', flavor: 'North is a habit. She will teach you a better one.', glyph: 'hero:kestrel' }),

  // Sable: sun, conducts long Chains.
  card({ id: 'sable.note', name: 'Hymn Note', kind: 'balanced', affinity: 'sun', cost: 1, atk: 6, ward: 4, effects: [{ type: 'heal', amount: 1 }], keywords: ['linked'], plus: { atk: 8, ward: 5 }, tier: 'basic', source: 'hero', hero: 'sable', flavor: 'A ringing note that joins whatever came before it.', glyph: 'prop:staff' }),
  card({ id: 'sable.canticle', name: 'Canticle', kind: 'rite', affinity: 'sun', target: 'self', cost: 1, atk: 0, ward: 2, effects: [{ type: 'light', amount: 2 }, { type: 'heal', amount: 3 }], keywords: ['spent', 'linked'], plus: { effects: [{ type: 'light', amount: 3 }, { type: 'heal', amount: 4 }] }, tier: 'uncommon', source: 'hero', hero: 'sable', flavor: 'Everyone has a note. She listens until she hears it.', glyph: 'prop:staff' }),
  card({ id: 'sable.voices', name: 'Ten Thousand Voices', kind: 'strike', affinity: 'sun', target: 'allFoes', cost: 2, atk: 7, ward: 2, effects: [{ type: 'heal', amount: 4 }], keywords: ['linked'], plus: { atk: 10 }, tier: 'rare', source: 'hero', hero: 'sable', flavor: 'Her baton remembers every voice.', glyph: 'prop:staff' }),
  card({ id: 'sable.ult', name: 'Requiem for Noon', kind: 'strike', affinity: 'sun', target: 'allFoes', cost: 0, atk: 12, ward: 0, effects: [{ type: 'heal', amount: 8 }, { type: 'light', amount: 2 }], keywords: ['fleeting'], plus: { atk: 16 }, tier: 'special', source: 'ultimate', hero: 'sable', flavor: 'Her choir sings the sun back up.', glyph: 'hero:sable' }),

  // Brannoch: flame, builds walls out of Breaks.
  card({ id: 'brannoch.bash', name: 'Trowel Bash', kind: 'guard', affinity: 'flame', cost: 1, atk: 4, ward: 7, effects: [{ type: 'status', status: 'burn', stacks: 1 }], plus: { ward: 9, effects: [{ type: 'status', status: 'burn', stacks: 2 }] }, tier: 'basic', source: 'hero', hero: 'brannoch', flavor: 'A heavy swing of the mason’s trowel.', glyph: 'prop:trowel' }),
  card({ id: 'brannoch.mortar', name: 'Mortar Wall', kind: 'guard', affinity: 'flame', cost: 1, atk: 2, ward: 11, effects: [{ type: 'ward', amount: 4 }], plus: { ward: 14 }, tier: 'uncommon', source: 'hero', hero: 'brannoch', flavor: 'A wall is a promise you make with your back.', glyph: 'prop:trowel' }),
  card({ id: 'brannoch.stone', name: 'Foundation Stone', kind: 'strike', affinity: 'flame', cost: 2, atk: 14, ward: 3, effects: [{ type: 'status', status: 'burn', stacks: 3 }], plus: { atk: 18 }, tier: 'rare', source: 'hero', hero: 'brannoch', flavor: 'The first stone of the Anchor. He is still sorry.', glyph: 'prop:trowel' }),
  card({ id: 'brannoch.ult', name: 'Anchor Stone', kind: 'strike', affinity: 'flame', cost: 0, atk: 18, ward: 0, effects: [{ type: 'ward', amount: 12 }, { type: 'status', status: 'burn', stacks: 3 }], keywords: ['fleeting'], plus: { atk: 24 }, tier: 'special', source: 'ultimate', hero: 'brannoch', flavor: 'Dropped on one enemy. He draws fire afterwards.', glyph: 'hero:brannoch' }),

  // Nim: volt, charges everything before touching it.
  card({ id: 'nim.tap', name: 'Static Tap', kind: 'strike', affinity: 'volt', cost: 0, atk: 4, ward: 1, effects: [{ type: 'status', status: 'shock', stacks: 3 }], plus: { atk: 5, effects: [{ type: 'status', status: 'shock', stacks: 4 }] }, tier: 'basic', source: 'hero', hero: 'nim', flavor: 'A crackle of borrowed current.', glyph: 'prop:wire' }),
  card({ id: 'nim.wires', name: 'Crossed Wires', kind: 'rite', affinity: 'volt', cost: 1, atk: 0, ward: 1, effects: [{ type: 'status', status: 'shock', stacks: 4 }, { type: 'status', status: 'chill', stacks: 1 }, { type: 'draw', count: 1 }], plus: { effects: [{ type: 'status', status: 'shock', stacks: 6 }, { type: 'status', status: 'chill', stacks: 1 }, { type: 'draw', count: 1 }] }, tier: 'uncommon', source: 'hero', hero: 'nim', flavor: 'Somebody is always listening.', glyph: 'prop:wire' }),
  card({ id: 'nim.blackout', name: 'Blackout', kind: 'strike', affinity: 'volt', target: 'allFoes', cost: 2, atk: 5, ward: 1, effects: [{ type: 'status', status: 'shock', stacks: 4 }, { type: 'status', status: 'chill', stacks: 1 }], plus: { atk: 7 }, tier: 'rare', source: 'hero', hero: 'nim', flavor: 'Every wire goes dark at once.', glyph: 'prop:wire' }),
  card({ id: 'nim.ult', name: 'Dead Line', kind: 'strike', affinity: 'volt', target: 'allFoes', cost: 0, atk: 8, ward: 0, effects: [{ type: 'status', status: 'shock', stacks: 5 }, { type: 'status', status: 'chill', stacks: 1 }], keywords: ['fleeting'], plus: { atk: 11 }, tier: 'special', source: 'ultimate', hero: 'nim', flavor: 'She speaks to ghosts now, since the cities are gone.', glyph: 'hero:nim' }),

  // Ondrej: moon, pries Shells open.
  card({ id: 'ondrej.lantern', name: 'Shuttered Lantern', kind: 'balanced', affinity: 'moon', cost: 1, atk: 4, ward: 4, effects: [{ type: 'crack', amount: 1 }], plus: { atk: 6, ward: 5 }, tier: 'basic', source: 'hero', hero: 'ondrej', flavor: 'A swing of the covered lamp.', glyph: 'prop:orb' }),
  card({ id: 'ondrej.pry', name: 'Pry Open', kind: 'strike', affinity: 'moon', cost: 1, atk: 4, ward: 1, effects: [{ type: 'crack', amount: 2 }], plus: { atk: 6 }, tier: 'uncommon', source: 'hero', hero: 'ondrej', flavor: 'A crowbar of pure dark.', glyph: 'prop:orb' }),
  card({ id: 'ondrej.dark', name: 'Dark of the Moon', kind: 'rite', affinity: 'moon', target: 'allFoes', cost: 2, atk: 0, ward: 3, effects: [{ type: 'crack', amount: 2 }, { type: 'status', status: 'hex', stacks: 1 }], plus: { effects: [{ type: 'crack', amount: 3 }, { type: 'status', status: 'hex', stacks: 1 }] }, tier: 'rare', source: 'hero', hero: 'ondrej', flavor: 'The lamp opens, and there is only night.', glyph: 'prop:orb' }),
  card({ id: 'ondrej.ult', name: 'Night Porter', kind: 'strike', affinity: 'moon', target: 'allFoes', cost: 0, atk: 9, ward: 0, effects: [{ type: 'crack', amount: 3 }, { type: 'status', status: 'hex', stacks: 1 }], keywords: ['fleeting'], plus: { atk: 12 }, tier: 'special', source: 'ultimate', hero: 'ondrej', flavor: 'Dark is only a door nobody has opened.', glyph: 'hero:ondrej' }),
];

// ---------------------------------------------------------------------------
// Heroes
// ---------------------------------------------------------------------------

export const HEROES: readonly HeroDef[] = [
  {
    id: 'wren',
    name: 'Wren',
    title: 'Apprentice Lamplighter',
    origin: 'story',
    rarity: 4,
    role: 'support',
    affinity: 'sun',
    hp: 74,
    starter: STARTER('wren.swing'),
    signature: ['wren.rekindle', 'wren.vigil'],
    ultimate: 'wren.ult',
    trait: { name: 'Warm Hands', passives: [{ type: 'breakHeal', value: 3 }, { type: 'victoryHeal', value: 3 }] },
    blurb: "Vesper's youngest Lamplighter. Wren can coax a Gloamstone awake, which is either a gift or a problem depending on who is asking.",
    quote: 'Hold the light steady. Everything else can shake.',
    look: { height: 0.96, style: 'shonen', hair: 'spiky', hairColor: '#4A2E24', skin: '#EBC3A2', eyes: '#E8A23A', outfit: '#2A1D2B', under: '#E9DFCB', accent: '#E0457B', prop: 'lantern', wear: ['scarf', 'gloves'] },
  },
  {
    id: 'io',
    name: 'Io',
    title: 'The First Afterlight',
    origin: 'story',
    rarity: 5,
    role: 'striker',
    affinity: 'moon',
    hp: 64,
    starter: STARTER('io.cut'),
    signature: ['io.turning', 'io.lidless'],
    ultimate: 'io.ult',
    trait: { name: 'Old Light', passives: [{ type: 'damage', pct: 0.1 }] },
    turning: 'The First Turning',
    blurb: 'A girl from the very first Turning, when the world still moved. She remembers a sunrise and cannot make anyone believe her.',
    quote: 'You call it the Stillness. I call it a very long afternoon.',
    look: { height: 1.02, style: 'rival', hair: 'hime', hairColor: '#DCD6F0', skin: '#F1E2D8', eyes: '#8FA0FF', outfit: '#1B1830', under: '#E6E1F2', accent: '#8FA0FF', prop: 'blade', wear: ['coat'] },
  },
  {
    id: 'marisol',
    name: 'Marisol Vey',
    title: 'Captain of Vesper',
    origin: 'story',
    rarity: 4,
    role: 'defender',
    affinity: 'volt',
    hp: 80,
    starter: STARTER('marisol.jab'),
    signature: ['marisol.ward', 'marisol.anchor'],
    ultimate: 'marisol.ult',
    trait: { name: 'Rail Guard', passives: [{ type: 'heldWard', value: 2 }] },
    blurb: 'Captain of the oldest, smallest Strider on the Duskline. She keeps the crew fed, the legs oiled, and the secrets to herself.',
    quote: 'Nobody gets left behind on my deck. Not even the ones who deserve it.',
    look: { height: 1.08, style: 'sukeban', hair: 'regent', hairColor: '#15121F', skin: '#C08A62', eyes: '#F2C23A', outfit: '#2B2320', under: '#1F2A3A', accent: '#F2C23A', prop: 'rail', wear: ['draped', 'plaster', 'longskirt'] },
  },
  {
    id: 'tamsin',
    name: 'Tamsin',
    title: 'Hushborn Scout',
    origin: 'story',
    rarity: 4,
    role: 'debuffer',
    affinity: 'frost',
    hp: 68,
    starter: STARTER('tamsin.needle'),
    signature: ['tamsin.bind', 'tamsin.night'],
    ultimate: 'tamsin.ult',
    trait: { name: 'Cold Read', passives: [{ type: 'startStatus', status: 'chill', stacks: 1 }] },
    blurb: 'A scout from the night side whose glowing tattoos map the stars from before the Stillness. She trusts stars more than people.',
    quote: 'The sky moved once. My skin remembers.',
    look: { height: 1.02, style: 'kunoichi', hair: 'bob', hairColor: '#0E2433', skin: '#D3B29A', eyes: '#57E0D0', outfit: '#141C30', under: '#2B3A55', accent: '#57E0D0', prop: 'needle', wear: ['mask', 'wraps', 'tattoos', 'headband'] },
  },
  {
    id: 'aurelian',
    name: 'Aurelian',
    title: 'Knight of the Meridian Dominion',
    origin: 'story',
    rarity: 4,
    role: 'burst',
    affinity: 'flame',
    hp: 66,
    starter: STARTER('aurelian.blade'),
    signature: ['aurelian.cleave', 'aurelian.verdict'],
    ultimate: 'aurelian.ult',
    trait: { name: 'Meridian', passives: [{ type: 'firstStrike', value: 2 }] },
    blurb: 'A Dominion knight sent to stop the climb, who read the Unturning’s scripture on the way up and put down his orders.',
    quote: 'I was taught the Stillness was mercy. Mercy should not look like this.',
    look: { height: 1.12, style: 'bishonen', hair: 'flowing', hairColor: '#E7B75A', skin: '#E6C4A0', eyes: '#D0463A', outfit: '#E9E2D2', under: '#B9A36F', accent: '#C8322C', prop: 'greatsword', wear: ['armor'], cape: true },
  },
  {
    id: 'pip',
    name: 'Pip',
    title: 'Salvager',
    origin: 'story',
    rarity: 4,
    role: 'healer',
    affinity: 'gale',
    hp: 66,
    starter: STARTER('pip.snap'),
    signature: ['pip.patch', 'pip.gale'],
    ultimate: 'pip.ult',
    trait: { name: 'Salvage', passives: [{ type: 'victoryHeal', value: 3 }, { type: 'emberGain', pct: 0.25 }] },
    blurb: "Salvage kid with a clockwork kite, picking lamp-glass off the Gnomon’s stairs. Everyone's little sibling, whether they like it or not.",
    quote: "If it's broken, I can fix it. If it's not broken, I can improve it until it is.",
    look: { height: 0.86, style: 'chibi', hair: 'puff', hairColor: '#7BD3B5', skin: '#E2B38C', eyes: '#F28A3A', outfit: '#1E3A3A', under: '#F2E3C4', accent: '#F28A3A', prop: 'kite', wear: ['goggles', 'overalls'] },
  },
  {
    id: 'ysolde',
    name: 'Ysolde Marrow',
    title: 'The Tidewarden',
    origin: 'afterlight',
    rarity: 5,
    role: 'defender',
    affinity: 'frost',
    hp: 84,
    starter: STARTER('ysolde.buoy'),
    signature: ['ysolde.tidewall', 'ysolde.undertow'],
    ultimate: 'ysolde.ult',
    trait: { name: 'Tidewall', passives: [{ type: 'startWard', value: 6 }, { type: 'heldWard', value: 1 }, { type: 'damage', pct: 0.15 }] },
    turning: 'The Sea Turning',
    blurb: 'She kept the lantern-buoys that guided ships home when the sea still moved. She kept them lit for a thousand years after the sea forgot.',
    quote: 'Follow the light. It has never once lied to me.',
    look: { height: 1.1, style: 'seinen', hair: 'windswept', hairColor: '#B7E2F0', skin: '#E2D0C4', eyes: '#5FB8D8', outfit: '#0F2A3A', under: '#35505E', accent: '#8FE3F5', prop: 'buoy', wear: ['cloak'] },
  },
  {
    id: 'kestrel',
    name: 'Kestrel Onwe',
    title: 'The Last Cartographer',
    origin: 'afterlight',
    rarity: 5,
    role: 'breaker',
    affinity: 'gale',
    hp: 66,
    starter: STARTER('kestrel.cut'),
    signature: ['kestrel.bearing', 'kestrel.roads'],
    ultimate: 'kestrel.ult',
    trait: { name: 'True North', passives: [{ type: 'shellBonus', value: 1 }] },
    turning: 'The Surveyors’ Turning',
    blurb: 'The last person to map a world that stayed the same for a whole lifetime. Her maps are now wrong in every way she is grateful for.',
    quote: 'North is a habit. I will teach you a better one.',
    look: { height: 1.04, style: 'showa', hair: 'explorer', hairColor: '#B25E36', skin: '#D4A27E', eyes: '#2A1A14', outfit: '#2F4A3A', under: '#E8D9B5', accent: '#F2D07A', prop: 'compass', wear: ['hat', 'satchel'] },
  },
  {
    id: 'sable',
    name: 'Sable Ardent',
    title: 'The Choirmaster',
    origin: 'afterlight',
    rarity: 5,
    role: 'support',
    affinity: 'sun',
    hp: 70,
    starter: STARTER('sable.note'),
    signature: ['sable.canticle', 'sable.voices'],
    ultimate: 'sable.ult',
    trait: { name: 'Conductor', passives: [{ type: 'chainBonus', pct: 0.1 }, { type: 'damage', pct: 0.1 }, { type: 'gaugeGain', pct: 0.25 }] },
    turning: 'The Choral Turning',
    blurb: 'Conducted a choir of ten thousand under a moving sun. Her baton remembers every voice.',
    quote: 'Everyone has a note. I just listen until I hear it.',
    look: { height: 1.06, style: 'shoujo', hair: 'curls', hairColor: '#2A1E33', skin: '#B48160', eyes: '#E8B04A', outfit: '#E8DCC0', under: '#7A1E2A', accent: '#C8322C', prop: 'baton', wear: ['epaulettes', 'tiara'], cape: true },
  },
  {
    id: 'brannoch',
    name: 'Brannoch Grey',
    title: 'The Ashmason',
    origin: 'afterlight',
    rarity: 4,
    role: 'defender',
    affinity: 'flame',
    hp: 82,
    starter: STARTER('brannoch.bash'),
    signature: ['brannoch.mortar', 'brannoch.stone'],
    ultimate: 'brannoch.ult',
    trait: { name: 'Mortar', passives: [{ type: 'breakWard', value: 5 }] },
    turning: 'The Builders’ Turning',
    blurb: 'Laid the first stones of the Anchor and has been quietly regretting its foundations ever since.',
    quote: 'A wall is a promise you make with your back.',
    look: { height: 1.16, style: 'gekiga', hair: 'crop', hairColor: '#6E6C78', skin: '#CFA07E', eyes: '#8A9AA8', outfit: '#6B4A32', under: '#D9D0BE', accent: '#F26B3A', prop: 'trowel', wear: ['apron', 'beard'] },
  },
  {
    id: 'nim',
    name: 'Nim Calloway',
    title: 'The Wire-witch',
    origin: 'afterlight',
    rarity: 4,
    role: 'debuffer',
    affinity: 'volt',
    hp: 66,
    starter: STARTER('nim.tap'),
    signature: ['nim.wires', 'nim.blackout'],
    ultimate: 'nim.ult',
    trait: { name: 'Crossed Wires', passives: [{ type: 'startStatus', status: 'shock', stacks: 5 }, { type: 'damage', pct: 0.1 }] },
    turning: 'The Wired Turning',
    blurb: 'Strung wires between cities so people could speak across the world. Speaks to ghosts now, since the cities are gone.',
    quote: "Somebody's always listening. I make sure it's someone kind.",
    look: { height: 0.98, style: 'majokko', hair: 'twintails', hairColor: '#4B3A9E', skin: '#DDB898', eyes: '#F2D24A', outfit: '#1D1A3A', under: '#EDE6F8', accent: '#F2D24A', prop: 'wire', wear: ['witchhat', 'frills'] },
  },
  {
    id: 'ondrej',
    name: 'Ondrej Vale',
    title: 'The Night-porter',
    origin: 'afterlight',
    rarity: 4,
    role: 'breaker',
    affinity: 'moon',
    hp: 72,
    starter: STARTER('ondrej.lantern'),
    signature: ['ondrej.pry', 'ondrej.dark'],
    ultimate: 'ondrej.ult',
    trait: { name: 'Night Shift', passives: [{ type: 'breakDraw', value: 1 }] },
    turning: 'The Long Night',
    blurb: 'Carried lanterns for travelers through a night that lasted forty years. Does not sleep. Does not mind.',
    quote: 'Dark is only a door nobody has opened.',
    look: { height: 1.05, style: 'yokai', hair: 'hooded', hairColor: '#20223A', skin: '#C9A386', eyes: '#9AA7FF', outfit: '#12131F', under: '#3A3B5A', accent: '#9AA7FF', prop: 'chochin', wear: ['haori'] },
  },
];
