import type { EncounterDef, StageDef } from '@duskline/core';

export const ENCOUNTERS: readonly EncounterDef[] = [
  { id: 'enc.0-1', name: 'Two Wisps', foes: [{ enemy: 'wisp' }, { enemy: 'wisp' }] },
  { id: 'enc.0-2', name: 'Wisps and a Wraith', foes: [{ enemy: 'wisp' }, { enemy: 'wraith' }, { enemy: 'wisp' }] },
  { id: 'enc.1-1', name: 'Salvage Ambush', foes: [{ enemy: 'wraith' }, { enemy: 'hound' }, { enemy: 'wraith' }] },
  { id: 'enc.1-2', name: 'Hush Road Pack', foes: [{ enemy: 'hound' }, { enemy: 'choir' }, { enemy: 'hound' }] },
  { id: 'enc.1-3', name: 'Husk in the Fog', foes: [{ enemy: 'wisp' }, { enemy: 'husk' }, { enemy: 'wisp' }] },
  { id: 'enc.1-4', name: 'Meridian Envoy', foes: [{ enemy: 'hound' }, { enemy: 'static' }, { enemy: 'hound' }] },
  { id: 'enc.1-5', name: 'The Umbral Warden', foes: [{ enemy: 'choir', levelOffset: -1 }, { enemy: 'warden' }, { enemy: 'choir', levelOffset: -1 }] },
];

/** The campaign so far: a prologue and Chapter 1. */
export const STAGES: readonly StageDef[] = [
  {
    id: '0-1',
    chapter: 0,
    name: 'Vesper at Dusk',
    blurb: 'Something is crawling along the rail.',
    level: 1,
    encounter: 'enc.0-1',
    forcedParty: ['wren', 'marisol'],
    firstClearGloam: 60,
    xp: 40,
    before: [
      { who: 'narrator', text: 'Dusk over Vesper. The old Strider’s legs groan as it keeps pace with a sun that will never set.' },
      { who: 'marisol', text: 'Wren, eyes up. Something is crawling along the rail.' },
      { who: 'wren', text: 'Fades. Two of them. They’re drawn to the lamp.' },
      { who: 'marisol', text: 'Then we keep the lamp lit and everything else behind us.' },
    ],
    after: [
      { who: 'wren', text: 'They just came apart. Like paper in the rain.' },
      { who: 'marisol', text: 'Third pack this week. Something is shaking them loose from the Hush.' },
      { who: 'narrator', text: 'In the lantern-room, the Gloamstone Wren carries begins to glow on its own.' },
    ],
  },
  {
    id: '0-2',
    chapter: 0,
    name: 'The Answering Lamp',
    blurb: 'The stone is warm. It has never been warm before.',
    level: 2,
    encounter: 'enc.0-2',
    firstClearGloam: 80,
    xp: 60,
    before: [
      { who: 'io', text: 'Ah. The sun is stuck. That would explain the headache.' },
      { who: 'marisol', text: 'Who in the Hush are you?' },
      { who: 'io', text: 'Io. I think I used to be very old, or very early. Either way, hello.' },
      { who: 'wren', text: 'The Fades are back. Io, can you fight?' },
      { who: 'io', text: 'I remember how. Point me at something.' },
    ],
    after: [
      { who: 'io', text: 'You fight like people who have never lost anything they could not carry. Good. Keep it that way.' },
      { who: 'wren', text: 'You said the world used to move.' },
      { who: 'io', text: 'It did. And I am the only one here who has seen it. Don’t ask me to prove it yet.' },
    ],
  },
  {
    id: '1-1',
    chapter: 1,
    name: 'Salvage Run',
    blurb: 'Vesper needs parts, and the old wind-farm has them.',
    level: 3,
    encounter: 'enc.1-1',
    firstClearGloam: 100,
    xp: 80,
    unlocks: ['pip'],
    before: [
      { who: 'marisol', text: 'Vesper needs parts. The wreck of the old wind-farm is three hours off the Duskline.' },
      { who: 'pip', text: 'Two hours if you don’t mind me riding the kite!' },
      { who: 'marisol', text: 'I mind. Get down from there.' },
    ],
    after: [
      { who: 'pip', text: 'Nobody said there would be monsters. That’s a lie, everybody said there would be monsters. I just hoped they were exaggerating.' },
      { who: 'marisol', text: 'You’re on my crew now. Rules: don’t touch what you can’t fix, and never fix what you can’t touch.' },
      { who: 'pip', text: 'That doesn’t make any sense. I love it.' },
    ],
  },
  {
    id: '1-2',
    chapter: 1,
    name: 'The Hush Road',
    blurb: 'Past the Duskline the light falls off a cliff.',
    level: 4,
    encounter: 'enc.1-2',
    firstClearGloam: 100,
    xp: 100,
    unlocks: ['tamsin'],
    before: [
      { who: 'narrator', text: 'Beyond the Duskline the light drops away. Frost rims the road and the stars come out early.' },
      { who: 'tamsin', text: 'You’re loud. And you’re carrying a stone that hums. Both of those will get you killed.' },
      { who: 'wren', text: 'We’re heading for the Umbral Reach. The Fades are coming from there.' },
      { who: 'tamsin', text: 'Then you need someone who can read the sky. I’m not offering yet. Survive the next mile.' },
    ],
    after: [
      { who: 'tamsin', text: 'Fine. The stars say you’re either brave or very lucky. I’ll come along until I find out which.' },
      { who: 'io', text: 'Tamsin, your tattoos. Those are the old constellations. The ones from before.' },
      { who: 'tamsin', text: '…You can read them?' },
      { who: 'io', text: 'I can remember them. It’s not the same thing, but it is close.' },
    ],
  },
  {
    id: '1-3',
    chapter: 1,
    name: 'Husk in the Fog',
    blurb: 'A Fade the size of a wagon blocks the pass.',
    level: 5,
    encounter: 'enc.1-3',
    firstClearGloam: 120,
    xp: 120,
    before: [
      { who: 'narrator', text: 'A Fade the size of a wagon blocks the pass, built from a hundred lost coats and someone’s front door.' },
      { who: 'io', text: 'That one remembers a house. Don’t hit the door. Hit whatever is holding the door up.' },
      { who: 'pip', text: 'That is somehow the most useful thing anyone has ever said about a door.' },
    ],
    after: [
      { who: 'marisol', text: 'Note to self: never underestimate a haunted front door.' },
      { who: 'pip', text: 'Can I keep the knocker?' },
      { who: 'marisol', text: 'No.' },
    ],
  },
  {
    id: '1-4',
    chapter: 1,
    name: 'Meridian Envoy',
    blurb: 'A sun-white banner at the edge of the Reach.',
    level: 6,
    encounter: 'enc.1-4',
    firstClearGloam: 150,
    xp: 140,
    unlocks: ['aurelian'],
    before: [
      { who: 'narrator', text: 'A sun-white banner flutters at the edge of the Reach. The Dominion sent an envoy. The envoy brought Fades, or the Fades followed him.' },
      { who: 'aurelian', text: 'Lamplighters. By order of the Meridian Dominion, surrender the stone.' },
      { who: 'wren', text: 'It isn’t ours to surrender. It isn’t anybody’s.' },
      { who: 'aurelian', text: '…Then I am afraid I must insist.' },
    ],
    after: [
      { who: 'aurelian', text: 'Your stone stopped the Fades from consuming my patrol. The Dominion did not teach me what to do with that.' },
      { who: 'aurelian', text: 'I will accompany you until I understand. Formally. Under protest.' },
      { who: 'marisol', text: 'A knight under protest. Vesper finally feels like a proper ship.' },
    ],
  },
  {
    id: '1-5',
    chapter: 1,
    name: 'The Umbral Warden',
    blurb: 'At the foot of the Reach, a figure of black paper waits.',
    level: 7,
    encounter: 'enc.1-5',
    firstClearGloam: 250,
    xp: 160,
    before: [
      { who: 'narrator', text: 'At the foot of the Umbral Reach, a figure of black paper and static waits, wearing a name it has forgotten.' },
      { who: 'The Umbral Warden', text: 'I was a keeper of records. Then the records stopped, and so did I.' },
      { who: 'io', text: 'It remembers being a person. That is the worst kind of Fade.' },
      { who: 'wren', text: 'Then we do this right. We give it something to remember.' },
    ],
    after: [
      { who: 'narrator', text: 'The Warden comes apart, and where it stood a single page drifts down, blank except for one word: STILL?' },
      { who: 'io', text: 'Someone stopped the world on purpose, Wren. And they wrote down why.' },
      { who: 'wren', text: 'Then we’re going to read it.' },
      { who: 'narrator', text: 'End of Chapter 1. More of the Duskline is on the way.' },
    ],
  },
];
